### ISSUE TITLE
mindreader provides --port 30305 is provided even if overridden

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-ethereum#2]
I have mindreader-node-arguments: "+--port=30301 --cache=2048"

ps shows me 

`/usr/bin/bsc-geth --networkid=56 --datadir=/var/lib/geth --ipcpath=/var/lib/dfuse/sf/ipc --port=30305 --rpc --rpcapi=admin,debug,eth,net,web3 --rpcport=8547 --rpcaddr=0.0.0.0 --rpcvhosts=* --nousb --firehose-deep-mind --port=30301 --cache=2048`

Notice there are two --port arguments.  It seems to work by taking the last one, but would like to avoid passing the first one anyway.

**Comment by matthewdarwin** [comment]
And yes, I know you can override the entire command line by not using "+"

**Comment by sduchesneau** [comment]
sf-eth allows you to run a full stack "all-in-one", including a miner node and a mindreader node, with default flags.
To allow this to run seemlessly with a simple `sfeth init && sfeth start`, we had to bundle some templating for the flags that are given to geth (or openethereum, or other flavours)

The code is here:
https://github.com/streamingfast/sf-ethereum/blob/develop/cmd/sfeth/cli/node.go#L232-L248

While we could lots of work into that templating system and add more flags for those default values, the added complexity (and effort) did not seem a worthy effort, since:
A) The `+` mechanism allows the simplest way to add a flag or override a value, which is the most common minor modification we've had to do (and it *WORKS* because geth parses all  the options and keeps the last value for repeated terms)
B) To prevent repetitions or misleading flags while looking at the process on the server, you can override the entire command by removing the + sign, and then STILL benefit from the templates.

The proper solution in your case would be to add this flag (with the tokens as-is, they will be replaced in the code):

```--mindreader-node-arguments='--networkid={network-id} --datadir={node-data-dir} --ipcpath={node-ipc-path} --port=30301 --http --http.api=eth,net,web3 --http.port=8547 --http.addr=0.0.0.0 --http.vhosts=* --nousb --firehose-deep-mind```

(note that I've also removed the admin,debug from rpcapi, as per #1)
(you can probably remove --nousb too, since it is now a deprecated flag)

I am not completely closed to the idea, of course, so I would consider a PR that implements a more elegant solution without increasing complexity for most use cases.

**Comment by maoueh** [comment]
I think the current solution is works good enough and we can close this.
