### ISSUE TITLE
cannot get lib num from blockstream

### ISSUE THREAD

**Issue by Qjawko** [streamingfast/firehose-ethereum#30]
When I'm trying to connect to GRPC server using method Blocks(ctx, req, opts...) there is an error:

`(firehose) cannot get lib num from blockstream, retrying {"retries": 4, "error": "tracking fetch errors in order: tracker block not found"}`

sf.yaml config:

      args:
        #    - merger
        #    - mindreader-node
        #    - relayer
      - firehose
      flags:
        common-blockstream-addr: :9002
        firehose-grpc-listen-addr: :9000
        common-chain-id: "56"
        common-network-id: "56"
        mindreader-node-bootstrap-data-url: ./mindreader/genesis.json
        mindreader-node-log-to-zap: false
        mindreader-node-arguments: *skipped*

**Comment by maoueh** [comment]
Hmm sorry for such long delay, have you succeed in solving your problem?

**Comment by sduchesneau** [comment]
"Older" versions of the firehose used try to sync from a block stream (either the mindreader directly, or the relayer) to "track" what is the current head of the chain and determine if it is ready to serve data.

With your configuration, it is understandable that it couldn't connect (unless you had another process listening on port 9002). 
If you want to run the firehose without a live source, you should set an empty string as the `common-blockstream-addr`.

Since [v1.0.0](https://github.com/streamingfast/firehose-ethereum/releases/tag/v1.0.0), there isn't any concept of "tracker" anymore, so you shouldn't see this error.

Since this affects an older version, I will go ahead and close this issue, feel free to comment on it to open again if you need more help!
